### ISSUE TITLE
Choose Where to Sync Notes

### ISSUE THREAD

**Issue by giittyy** [mysticcoders/voicenotes-sync#13]
Add ability to sync notes to daily note or a specific note and the option to sync under a specific heading in the note.

**Comment by kinabalu** [comment]
have you seen something similar done for other processes? trying to work out how we can make this happen. does this work with Periodic Notes plugin only? how would you envision this working?

**Comment by qwertydude** [comment]
My thought on this would be use the tags from VN. e.g. if I tagged a note dailynote, then it'd be appended to the relevant daily note.

I did something similar with Shortcuts and use a comment rather than a heading to pinpoint where to insert. So, my daily note template has comments like %%dailyjournal%% (under the Journal heading) or %%dailytodo%% (under the To Do heading) in it.

**Comment by kinabalu** [comment]
interesting. would likely have to standardize on the convention -- is %%dailyjournal%% something that you used with Templater?

always happy to for any PRs if you'd like to take a stab at it

**Comment by qwertydude** [comment]
I think I used that because that worked best with Actions for Obsidian in Apple Shortcuts. I think I've seen ways to insert under headings tho. Haven't done much Obsidian coding (Dataview, Templater, Shortcuts) for a bit tho, so memory is rusty.

**Comment by kinabalu** [comment]
yeah no worries -- thinking through this a bit to see best way -- i think initially we'll add a command which can be used to insert any of today's voicenotes as a bulleted list after executing in the editor.
