### ISSUE TITLE
Syncing not happening

### ISSUE THREAD

**Issue by qwertydude** [mysticcoders/voicenotes-sync#14]
Syncing is not working and when I open the developer console, it says login failed to return JSON.

![image](https://github.com/mysticcoders/voicenotes-sync/assets/129821/9ab1c15d-4449-4db5-9d95-bbf33004c4e5)

Obsidian: 1.5.12
Voicenotes Sync: 0.0.9

I originally signed up with Voicenotes using Apple ID. In Voicenotes Sync, I'm using its email and password.

**Comment by kinabalu** [comment]
Ok, so the settings login won't actually work for the secondary login methods they provide since this is an OAuth transition that happens server side. 

Steps to login (quite manual but doable).

1. Open up voicenotes.com in a browser like Chrome
2. After logging in open up Developer Tools
3. Navigate to the "Network" tab
4. Click on Fetch/XHR to see those calls specifically
5. Hit refresh on the voicenotes.com page
6. One of the entries should say "me" click on it and navigate to the Headers section
7. Scroll down to "Request Headers" and find the line that says "Authorization"
8. The right side of this entry will say "Bearer x" where x is a longish string of text. This is your authorization / login key
9. Copy that value for the next step

# Back in Obsidian
1. Disable Voicenotes Sync plugin in Obsidian
2. Navigate to the `.obsidian/plugins/voicenotes-sync` directory in your vault on the filesystem
3. Open up `data.json` in an editor of your choice
10. The value of the `token` field needs to contain the entire bit after `Bearer` in previous stage

**Comment by qwertydude** [comment]
Thanks! That mostly worked. It's only downloaded 10 notes. Which, when I test in Insomnia, I see the "per page" is set to 10.

Any trick to get it to download all?

Also, notice tags are imported and assigned. Is that on the todo list?

**Comment by kinabalu** [comment]
#4 will resolve the download all issue (and usually will happen only on first sync or if you hit "manual sync") btw how many pages of voicenotes do you have? just trying to gauge

and #17 i just created so we can add tags to the notes (i think this wasn't there when I first wrote this)

**Comment by kinabalu** [comment]
#4 and #17 are both resolved now in 0.0.10. Thank you

**Comment by qwertydude** [comment]
Thanks for all that! Just bought you a coffee. Great work!

Five pages of Voicenotes btw.
